# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Moreno
title: CTO & Technology Leader
email: me@martinmoreno.me
website: www.martinmoreno.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: martin-moreno-84106924
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me_cartoon_3.png
about_content: | # this will include new lines to allow paragraphs
  I'm a technology leader with 20+ years experience building high-impact digital solutions and leading global engineering teams. 
  
  Passionate about creating testable architectures that scale, fostering technical excellence, and bridging the gap between business objectives and engineering execution.
  
  Recognized for building high-performance teams that deliver market-leading mobile applications and cloud infrastructure.

# Content
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Workfully
        sub_title: CTO
        caption: Oct 2023 - Present | Barcelona
        quote: >
          Workfully is a B2B Marketplace set to replace recruiting agencies through its technology platform.
        description: |
          Lead the engineering team formation and infrastructure design at Workfully, using the AWS ecosystems to support enterprise-grade applications. 
          
          Combined technical roadmaps with business objectives with clean, testable system designs, while mentoring cross-functional teams in DevOps best practices and agile delivery.

      - layout: left
        title: OLX Group
        sub_title: Head of Engineering
        caption: March 2022 - Aug 2023 | Barcelona
        quote: >
          We help millions of people buy and sell cars, find housing, get jobs, buy and sell household goods, and much more.
        description: |
          - Led the App-in-App Project, which unified both the most massive app in
          OLX Group (35M MAU) with the top revenue driver app of the Group.
          - Led the Cars Catalog team, which handled car inventory across all
          operating markets.
          - Created the onboarding process for the Barcelona Hub.
           - Participated in the design of the Hiring Process for the Barcelona Hub.

      - layout: left
        title: OLX Group
        sub_title: Engineering Manager
        caption: July 2021 - March 2022 | Barcelona
        description: |
          - Led Pay & Ship Team creating shipping/billing platform for Turkish market

      - layout: left
        title: OLX Group
        sub_title: Technical Lead
        caption: Sept 2019 - July 2021 | Lisbon
        description: |
          - Designed and created Android and iOS CI pipelines.
          - Led the design and creation of Seller Review Microservice.

      - layout: left
        title: OLX Group
        sub_title: Android Chapter Lead
        caption: Aug 2018 - Aug 2019 | Buenos Aires
        description: |
          - Led Android Architectural refactor from Big Ball of Mud to Clean/Layer Architecture while continuing to deliver features for 20 million Monthly Active Users.
          - Lead with teams in different parts of the globe (Argentina, Portugal, Berlin, and India).
          - Collaborated on the iOS Architectural refactor.

      - layout: left
        title: ETERMAX
        sub_title: Technical Owner
        caption: Feb 2017 - Oct 2018 | Buenos Aires
        description: |
          - Design end-to-end mobile game using DynamoDB, Docker Swarm, Kotlin backend, and Unity frontend.
          - Build, train, and manage a six engineering team to implement and maintain the solution.
          - Hire an engineering team from scratch in a new company hub.

      - layout: left
        title: ARTEAR
        sub_title: Technical Lead
        caption: Apr 2014 - Feb 2017 | Buenos Aires
        description: |
          - Break apart a legacy PHP monolith into microservices.
          - Hire and grow an Android and iOS team.
          - Design Android and iOS apps from scratch, including APIs.

      - layout: left
        title: GLOBANT
        sub_title: Technical Lead Mobile
        caption: Jan 2011 - Apr 2014 | Buenos Aires
        description: |
          - Created Android games with native and LibGDX libraries.

      - layout: left
        title: Nextive
        sub_title: Software Designer
        caption: Jan 2010 - Jan 2011 | Buenos Aires
        description: |
          - Created Facebook games, mainly in Adobe Flash and other web technologies.

      - layout: left
        title: Sabarasa Entertainment
        sub_title: Programmer
        caption: Dec 2009 - Dec 2010 | Buenos Aires
        description: |
          - Writing Games for Nintendo DS using C++ and an in-house Engine.
          - Writing Games for Nintendo Wii, using C++ and Torque3D Engine.

      - layout: left
        title: Image Campus
        sub_title: Web Programmer Lead
        caption: Jan 2006 - Dec 2009 | Buenos Aires
        description: |
          - Created the internal system and web for the university.
          - Hired a small web team.

      - layout: left
        title: Austral Games
        sub_title: Web Programmer
        caption: Aug 2003 - Dec 2005 | Buenos Aires
        description: |
          - Developed company website and game assets
          - Created maps for "Federacion 2073" game

  - title: Technical Skills
    layout: text
    content: |
      **Core Competencies:**
      - Clean Architecture, DDD, TDD
      - Kotlin/Java/PHP/JS/Typescript/Python/Ruby/C++
      - AWS, CDK, Cloudformation
      - Android/iOS Development

      **Leadership:**
      - Team building & mentorship
      - Cross-functional collaboration
      - Cloud Architecture 
      - Technical roadmap planning

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme
livereload: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
